---
--- Generated by Luanalysis
--- Created by chz.
--- DateTime: 2024/4/7 21:02
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId
--判断库存
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
-- 判断下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 下单
redis.call('sadd', orderKey, userId)
return 0

